.TH "XML Copy Editor" "1" "" "" ""
.SH "NAME"
xmlcopyeditor \- fast, free, validating XML editor
.SH "SYNOPSIS"
.B xmlcopyeditor
.BI  [ \-\-version ]
.BI  [ \-\-help ]
.BI  [ <file> ]
.BI  [ <file2> ]
.SH "DESCRIPTION"
.I XML Copy Editor
is an XML editor focusing on editing document markup languages like DITA, DocBook, WordprocessingML. It features DTD/XML Schema/RELAX NG validation, XSLT, XPath, pretty\-printing, syntax highlighting, folding, tag completion/locking, a spelling/style check and, on Windows, lossless import/export of Microsoft Word documents.
.PP 
.I XML Copy Editor
is free software released under the GNU General Public License.
.SH "AUTHOR"
Gerald Schmidt (gnschmidt@users.sourceforge.net)
.SH "SEE ALSO"
You can find more information in the
.I Help
menu inside the program and in its homepage at
http://xml\-copy\-editor.sourceforge.net/
